ACTION_WEIGHTS:
  ACTION: 1.0
LOG_TO_FILE: True
BATCH_SIZE: 32
DATASET_TYPE: video
VIDEOS_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/dataset.hdf5
EXPERIMENT_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2023_data/something-something-detections
LABELS_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something-something-v2-labels.json
LOG_TO_FILE: False
MODEL_NAME: swin
TOTAL_ACTIONS:
  ACTION: 174
TRAIN_DATASET_NAME: something-something
VAL_DATASET_NAME: something-something
TRAIN_DATASET_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something_something_detections/train_dataset.json
VAL_DATASET_PATH: /esat/smcdata/users/kkontras/Image_Dataset/no_backup/Sth-Sth/something_something_detections/val_dataset.json
BATCH_SIZE: 128
FRAME_UNIFORM: True
NUM_FRAMES: 16
WEIGHT_DECAY: 0.02
LEARNING_RATE: 0.0001
EPOCHS: 30
WARMUP_EPOCHS: 3